.gitignore, babel.config.js, jest.config.ts, package-lock.json, package.json, tsconfig.json
=> chore: setup tooling

.github/workflows/ci.yml
I noticed that there is no CI, so I added a simple CI workflow which runs all unit tests
=> ci: add test workflow

Maths/Factorial.ts, Maths/test/Factorial.test.ts
- add Factorial
- add Factorial tests
#10
=> feat(maths): add `Factorial`

Maths/RadiansToDegrees.ts, Maths/test/RadiansToDegrees.test.ts
> * [x]  Radian to Degree conversion
#10
=> feat: Added Radian to Degree conversion

Sorts/BubbleSort.ts, Sorts/test/BubbleSort.test.ts
>*  [x] Algorithm: Bubble Sort
=> feat: Added Bubble sort

Sorts/InsertionSort.ts
Fix minor spelling typo in insertion sort algorithm
=> chore: fix spelling typo

Maths/SieveOfEratosthenes.ts, Maths/test/SieveOfEratosthenes.test.ts
Algorithm to find prime numbers
=> algorithm: sieve of erastosthenes

DIRECTORY.md
added Array Queue to the Directory.md which was not referenced
=> updated Directory.md

CONTRIBUTING.md
updated with the link to conventinal commits website for those who are new to this format
=> feat: update contribution.md file

DIRECTORY.md, maths/is_square_free.ts, maths/test/is_square_free.test.ts
#10 Added function to check a number is Square free.
=> feat: Function to check a number is Square free

sorts/selection_sort.ts, sorts/test/selection_sort.test.ts
I am submitting this pull request to add the selection sort algorithm to the algorithms repository. I believe this feature will be a valuable addition and provide a comprehensive resource for developers and students looking to learn or implement sorting algorithms.
I have thoroughly tested the implementation and have made sure that it follows the repository's coding standards and best practices. I would be happy to address any questions or concerns you may have about this pull request.
Thank you for your time and consideration. I am looking forward to your feedback.
=> Feat: add selection sort. closes #95

sorts/shell_sort.ts, sorts/test/shell_sort.test.ts, sorts/test/shell_sort.ts
Shell sort algorithm added with tests
=> feat: add shell sort

DIRECTORY.md, sorts/cycle_sort.ts, sorts/test/cycle_sort.test.ts
Adding cycle sort algorithm with test
=> feat: add cycle sort implementation

DIRECTORY.md, search/jump_search.ts, search/test/jump_search.test.ts
Add implementation of jump serach algorithm in typescript
=> feat: Add implementation of jump serach algorithm in typescript

maths/fibonacci.ts, maths/test/fibonacci.test.ts
Hi @raklaptudirm @appgurueu 
I added a method which calculates nth fibonacci number using formula.
Please review this.
Thank you !
=> feat : added fibonacci method using formula

search/sentinel_search.ts, search/test/sentinel_search.test.ts
Added Sentinel Search Algorithm.
=> feat: Added Sentinel Search

backtracking/test/all_combinations_of_size_k.test.ts, backtracking/test/generateparentheses.test.ts, maths/test/ugly_numbers.test.ts
=> fix: failing tests

dynamic_programming/lcs.ts, dynamic_programming/test/lcs.test.ts
I added feature of LCS implementation using tabluation approach in typescript
=> Feat : Longest Common Subsequence Implementation using Typescript

sorts/heap_sort.ts, sorts/test/heap_sort.test.ts
addition of the heap sort algorithm
=> Feat : Heap Sort

maths/gaussian_elimination.ts, maths/test/gaussian_elimination.test.ts
Adding feature to solve system of linear equations using guassian elimination method
=> Feat : Gaussian Elimination Method

graph/bipartite_graph.ts, graph/test/bipartite_graph.test.ts
Adding a new feature to check whether any graph is bipartite or not.
@appgurueu  @raklaptudirm  please review my PR
=> Feat : Bipartite Graph

sorts/quick_sort.ts
=> fix: Fix QuickSort

maths/euler_totient.ts, maths/test/euler_totient.test.ts
Add implementation of euler's totitent function mentioned here [#10](https://github.com/TheAlgorithms/TypeScript/issues/10)
=> Feat: add euler's totient function

sorts/heap_sort.ts
Everything is done in place. Space is constant.
=> fix: document heap sorts space complexity to O(1)

graph/tarjan.ts, graph/test/tarjan.test.ts
see https://en.wikipedia.org/wiki/Tarjan%27s_strongly_connected_components_algorithm
=> feat: add tarjan algorithm for strongly connected components

.github/workflows/upload_coverage_report.yml, .gitignore, DIRECTORY.md
This PR establishes the integration with [`codecov`](https://app.codecov.io/gh/TheAlgorithms/TypeScript/).
Is is very similar to TheAlgorithms/JavaScript#1599.
=> chore: add `upload_coverage_report.yml`

maths/test/square_root.test.ts
There is something strange with [`square_root.test.ts`](https://github.com/TheAlgorithms/TypeScript/blob/4f6cd6c264d047dcc1bf1045765f4d8968fee6d2/maths/test/square_root.test.ts). This PR fixes that.
=> test: fix `square_root.test.ts`

data_structures/heap/heap.ts
- Improved comments for clarity and correctness.
- Used default parameter values where applicable for better readability.
- Consistently used `void` return type for functions without a return value.
- Ensured consistent use of semicolons for statement termination.
- Made minor adjustments to ensure consistency in naming and coding style.
=> Minor style fix: Heap Implementation
