.github/CODEOWNERS
README.md

feat: improve repository structure

---

CONTRIBUTING.md

Fixes: #4
To add this contribution guidelines, I've used the contribution guidelines from the [JavaScript Repo](https://github.com/TheAlgorithms/JavaScript/blob/master/CONTRIBUTING.md). Then, I changed the JavaScript-related things for TypeScript-related ones. 
In the process, I've removed the test guidelines and some of the style guidelines because this project isn't fully set up yet. Also, I've used the [TypeScript Standard Style](https://github.com/standard/ts-standard) in the style guide and hope it was the right decision.
Thanks for opportunity of working on this project :)

Feat: add contribution guidelines

---

Sorts/InsertionSort.ts
Sorts/test/InsertionSort.test.ts

algorithm: insertion sort

---

Maths/AbsoluteValue.ts
Maths/test/AbsoluteValue.test.ts

Includes changes related to Issue: #10 
Included a new maths function to calculate the absolute value of numeric values, as well as associated tests

algorithm: AbsoluteValue

---

Search/BinarySearch.ts
Search/test/BinarySearch.test.ts

Added recursive and iterative implementations of binary search algorithm. Added jest unit tests for binary search.

Algorithm: Binary Search

---

Maths/IsLeapYear.ts
Maths/test/IsLeapYear.test.ts

- add `IsLeapYear` (gregorian calendar) and tests
#10

feat(maths): add `IsLeapYear`

---

CONTRIBUTING.md

I'm getting tired of making the same review comments over and over again.

Add guide on writing good tests

---

Maths/PerfectSquare.ts
Maths/test/PerfectSquare.test.ts

Added the case to check perfect square along with the test cases

[Feat] : Added perfect square

---

Maths/DigitSum.ts
Maths/test/DigitSum.test.ts

feat(maths): add `DigitSum`

---

Sorts/QuickSort.ts
Sorts/test/QuickSort.test.ts

Added Quick Sort along with the test cases.

[Feat] : Added Quick Sort

---

Sorts/MergeSort.ts
Sorts/test/MergeSort.test.ts

Added merge sort with the test cases.

[Feat] : Added merge sort

---

CONTRIBUTING.md
README.md

Use the new Discord invitation link specified in the related issue.
Closes #47

docs: replace all occurrences of Discord link

---

Maths/ArmstrongNumber.ts
Maths/test/ArmstrongNumber.test.ts

Added a function to check whether a number is an armstrong number or not

algorithm: check if number is Armstrong number

---

Maths/FindMin.ts
Maths/test/FindMin.test.ts

#10 : Adding IsMin feature, one of several requested.

algorithm: find min

---

Sorts/GnomeSort.ts
Sorts/test/GnomeSort.test.ts

Add a new algorithm called Gnome sort  that moving an element to its proper place is accomplished by a series of swap

algorithm: gnome sort

---

Data-Structures/Stack.ts
Maths/AliquotSum.ts
Maths/test/AliquotSum.test.ts

Added a function to return the aliquot sum of the given number
[Link](https://the-algorithms.com/algorithm/aliquot-sum) to the entry

algorithm: aliquot sum

---

CONTRIBUTING.md

`test` -> `describe` (`test` can't be nested)

Fix guide on writing good tests

---

dynamic_programing/Knapsack.ts
dynamic_programing/test/Knapsack.test.ts

Added the knapsack algorithm. All contribution guidelines followed.

algorithm: knapsack

---

Maths/LowestCommonMultiple.ts
Maths/test/LowestCommonMultiple.test.ts

algorithm: lcm

---

other/parse_nested_brackets.ts
other/test/parse_nested_brackets.test.ts

feat: add `parseNestedBrackets`

---

DIRECTORY.md
maths/signum.ts
maths/test/signum.test.ts

This PR aims to add the implementation for the signum function, also known as the sign function. The [link](https://the-algorithms.com/algorithm/signum) to the TheAlgorithms entry.

feat: Added signum 

---

DIRECTORY.md
maths/pronic_number.ts
maths/test/pronic_number.test.ts

This PR aims to add the implementation for checking whether a number is a pronic number of not. The related entry is [here](https://the-algorithms.com/algorithm/pronic-number)

algorithm: pronic number

---

data_structures/stack_queue.ts
data_structures/test/stack_queue.test.ts

- Added a Queue implementation with 2 Stacks. 
- The stacks used in the implementation are from the pre-existing stack implementation in `stack.ts`
- Utilized the pre-existing tests for Queue.
**Time Complexity**
| Operation | Time Complexity |
|-----------|-----------------|
| Enqueue   | O(1)            |
| Dequeue   | Amortized O(1)  |
| Peek      | Amortized O(1)  |

feat: add queue implementation using two stacks

---

maths/fibonacci.ts
maths/test/fibonacci.test.ts

This is an improvement to the algorithm for calculating the nth Fibonacci number, as the algorithm can be implemented recursively. Also, I have improved and structured the tests a bit different.
Feel free to share your thoughts and give feedback.

feat(maths): recursive calculating of Fibonacci numbers

---

data_structures/binary_search_tree.ts
data_structures/test/binary_search_tree.test.ts

This is an implementation of a binary search tree. If there are any inconveniences, please comment here, so I can improve the code.

feat(data-struct): binary search tree

---

maths/factors.ts
maths/test/factors.test.ts

This pull request improves the features/changes made in #103 and resolves the requested changes.
@T1LT Hope you are fine with it and thanks for adding this method!

feat(maths): finishes Factors

---

data_structures/queue/circular_queue.ts
data_structures/queue/test/circular_queue.test.ts

This PR implements a circular queue, which has already been started but never finished in #70 
Because we now have a general interface for the `Queue`, I decided to create a new branch with the implementation and create the `Circular Queue` with the already existing interface instead of fighting with potential merge conflicts.

feat(structure): implements circular queue

---

maths/perfect_cube.ts
maths/test/perfect_cube.test.ts

Implementation of a perfect cube.

feat: perfect cube

---

graph/bellman_ford.ts
graph/test/bellman_ford.test.ts

Add bellman-ford algorithm to find shortest paths from single source in a graph. It is able to detect negative weight cycles. See https://en.wikipedia.org/wiki/Bellman%E2%80%93Ford_algorithm

feat: add bellman-ford algorithm

---

data_structures/heap/max_heap.ts
data_structures/heap/min_heap.ts
data_structures/heap/test/max_heap.test.ts
data_structures/heap/test/min_heap.test.ts

MinHeap  would break if we extract from a heap of two elements that looks like
```
A
/    \
B    undef
```
It would bubble up the right child and get
```
undef
/
B
```
I added more tests for MinHeap that inserts/extracts everything, and would have failed before this patch. I also added equivalent tests for MaxHeap.

fix, test: Fix MinHeap sinkDown implementation, increase test coverage

---

graph/kruskal.ts
graph/test/kruskal.test.ts

add well-known kruskal's algorithm
Is it plagiarism to use test cases from other TheAlgorithms repos? I got testcases from https://github.com/TheAlgorithms/Rust/blob/master/src/graph/minimum_spanning_tree.rs to avoid having to come up with interesting graph cases myself. If this is a problem, I can rewrite stuff from scratch.

feat: add kruskal algorithm

---

sorts/quick_select.ts
sorts/test/quick_select.test.ts

QuickSelect is an efficient algorithm for finding the kth smallest element in an unsorted array. It uses a partitioning technique similar to QuickSort to divide the array and narrow down the search range. With an average time complexity of O(n), QuickSelect is a powerful tool for retrieving specific elements without sorting the entire array.

feat: add quick select algorithm and test #6

---

maths/binomial_coefficient.ts
maths/test/binomial_coefficient.test.ts

The BinomialCoefficient function calculates the binomial coefficient of two input numbers, representing the number of ways to choose k elements from a set of n elements. The function follows the mathematical formula for binomial coefficients and returns the computed value.
Please review the code  in this pull request. 
Changes Made:
- Added `BinomialCoefficient` function to calculate the binomial coefficient
- Added parameter validation and error handling
- Added tests for the `BinomialCoefficient` function

feat: added binomial coefficient function and the corresponding test #10

---

data_structures/heap/heap.ts
data_structures/heap/test/max_heap.test.ts
data_structures/heap/test/min_heap.test.ts
graph/dijkstra.ts
graph/test/dijkstra.test.ts

Add dijkstra shortest path algorithm for adjacency matrix.
We can get lower bounds on a graph with adjacency list representation using min/Fibonacci heap, but I think this solution is the lowest bound we can get for an adjacency matrix representation.

feat: add dijkstra with adjacency list and heap increasePriority

---

data_structures/heap/heap.ts
data_structures/heap/test/min_heap.test.ts
graph/prim.ts
graph/test/prim.test.ts

feat: add Prim's algorithm for Minimum Spanning Tree
fix: do not decrease priority in PriorityQueue increasePriority()

feat: add Prim's algorithm for Minimum Spanning Tree

---

backtracking/all-combinations-of-size-k.ts
backtracking/test/all-combinations-of-size-k.test.ts

Create all combinations of k numbers out of 1...n using backtracking

feat(backtracking): all combinations of k numbers out of 1...n

---

bit_manipulation/add_binary.ts
bit_manipulation/test/add_binary.test.ts

Adding a new feature to add 2 binary no.s using bit manipulation technique
@appgurueu  @raklaptudirm  please review my PR

Feat : Add Binary No.s

---

DIRECTORY.md
maths/matrix_multiplication.ts
maths/test/matrix_multiplication.test.ts

Ref #10 
Add new implementation for matrix-matrix, matrix-vector and matrix-scalar multiplication.

Feat(maths): add matrix multiplication

---

DIRECTORY.md
sorts/test/tree_sort.test.ts
sorts/tree_sort.ts

Adding tree sort algorithm with tests.

feat: add treesort algorithm

---

graph/kosajaru.ts
graph/test/kosajaru.test.ts

See https://en.wikipedia.org/wiki/Kosaraju%27s_algorithm
I found a couple of articles online that suggest that the space complexity is O(V), for creating a the visited array and priority stack. I think it should actually be O(V + E), because the transposed graph needs to hold E edges. I think my analysis is correct, but have not found any sources online to confirm it.

feat: Add kosajura algorithm for finding strong connected components

---

maths/test/is_palindrome.test.ts

This PR adds tests covering this line:
https://github.com/TheAlgorithms/TypeScript/blob/296e4a5af4bf4dc3a921db96bd95e82112d0bb38/maths/is_palindrome.ts#L11

tests: add missing tests of `isPalindrome`

---

maths/is_square_free.ts
maths/test/is_square_free.test.ts

The current implementation of [`isSquarefFree`](https://github.com/TheAlgorithms/TypeScript/blob/4f6cd6c264d047dcc1bf1045765f4d8968fee6d2/maths/is_square_free.ts#L11) returns `true` for `9 = 3*3`. This PR fixes that and adds missing tests and reorganizes them.

fix: handle squares properly in `isSquareFree`

---

backtracking/all_combinations_of_size_k.ts
bit_manipulation/add_binary.ts
data_structures/heap/heap.ts
data_structures/heap/test/heap.test.ts
data_structures/queue/linked_queue.ts
data_structures/stack/test/linked_list_stack.test.ts
dynamic_programming/knapsack.ts
graph/bellman_ford.ts
graph/dijkstra.ts
graph/floyd_warshall.ts
graph/johnson.ts
graph/kosajaru.ts
graph/kruskal.ts
graph/prim.ts
graph/tarjan.ts
graph/test/bellman_ford.test.ts
graph/test/dijkstra.test.ts
graph/test/floyd_warshall.test.ts
graph/test/johnson.test.ts
graph/test/kruskal.test.ts
graph/test/prim.test.ts
maths/calculate_median.ts
maths/matrix_multiplication.ts
maths/pascals_triangle.ts
maths/perfect_number.ts
maths/prime_factorization.ts
sorts/bubble_sort.ts
sorts/quick_select.ts
sorts/swap_sort.ts
sorts/test/merge_sort.test.ts

As suggested [here](https://github.com/TheAlgorithms/TypeScript/pull/229#pullrequestreview-1874379167), I stared exploring _linting_/static analysis tools available for TypeScript. The [TypeScipt eslint](https://typescript-eslint.io) seems to be reasonable. These changes are the result of running `npx eslint . --fix`, and from what I see it has changed `let` to `const`, which is a tiny step in a good direction.

style: use `const` when possible

---

maths/lowest_common_multiple.ts
maths/test/lowest_common_multiple.test.ts

This PR simplifies `binaryLCM` by removing redundant branches (they are present in `binaryGCF`).

style: simplify `binaryLCM`

---

dynamic_programming/knapsack.ts

Improve code readability, maintainability and edge case handling.
- Correctly throws an error if the length of the weights and values arrays are not equal
- Use camelCase consistently through the codebase
- Add type annotations to the function params and return types
- Adding comments within the loops to clarify the logic
- Ensure your function handles edge cases appropriately, such as when capacity is 0 or when weights and values arrays are empty

Refactor 0-1 Knapsack Implementation

---

DIRECTORY.md
README.md

Continuation of #224. This PR adds codecov badge.

Add codecov badge

---

graph/dijkstra.ts
search/jump_search.ts

This PR fixes some eslint warnings, namely:
```
/workspace/TypeScript/graph/dijkstra.ts
1:10  error  'MinHeap' is defined but never used     @typescript-eslint/no-unused-vars
35:18  error  '_' is assigned a value but never used  @typescript-eslint/no-unused-vars
```
and
```
/workspace/TypeScript/search/jump_search.ts
26:5  error  'stepSize' is never reassigned. Use 'const' instead  prefer-const
```
Continuation of #230.

style: fix some eslint warnings

---

dynamic_programming/coin_change.ts
graph/prim.ts
sorts/counting_sort.ts

In this PR I suggest to use `for-of` instead of the _basic_ `for` loop (in reasonable places).
Similar to:
- #230,
- #240.

style: use `for-of`

---

data_structures/tries/tries.ts

Does some basic linting of `tries.ts`.
Similar to:
- #230,
- #240,
- #241.

style: lint `tries.ts`

---

sorts/shell_sort.ts

Fixes the [array-type](https://typescript-eslint.io/rules/array-type/) warning.
Similar to:
- #230,
- #240,
- #241,
- #242.

style: use `T[]` instead of `Array<T>`

---

search/binary_search.ts
search/exponential_search.ts
search/test/binary_search.test.ts
search/test/exponential_search.test.ts

added exponential search and its related test.

Exponential search
